---
# Default variables for pxe-dnsmasq role

pxe_interface: "{{ ansible_default_ipv4.interface }}"
pxe_ip: "{{ ansible_default_ipv4.address }}"
dhcp_range_start: "192.168.100.50"
dhcp_range_end: "192.168.100.100"
dhcp_lease_time: "12h"
tftp_root: "/srv/tftp"

