---
# Default variables for pxe-ubuntu-netboot role

tftp_root: "/srv/tftp"
ubuntu_version: "22.04"
ubuntu_iso_url: "https://releases.ubuntu.com/22.04/ubuntu-22.04.4-live-server-amd64.iso"
ubuntu_iso_dest: "/tmp/ubuntu.iso"
iso_mount_point: "/mnt"

